# deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-example
  template:
    metadata:
      labels:
        app: devops-example
    spec:
      containers:
      - name: devops-example
        image: devops-example
        ports:
        - containerPort: 3000
