# service.yml
apiVersion: v1
kind: Service
metadata:
  name: devops-example-service
spec:
  selector:
    app: devops-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
